services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx_broker
    ports:
      - "1883:1883"
      - "8083:8083"
      - "18083:18083"
    restart: always
  web-client:
    image: nginx:alpine
    container_name: mqtt_web_client
    ports:
      - "8080:80"        
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
  zabbix-db:
    image: mysql:8.0
    container_name: zabbix_db
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    command: --character-set-server=utf8 --collation-server=utf8_bin
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix_server
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    depends_on:
      - zabbix-db
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:latest
    container_name: zabbix_web
    ports:
      - "8081:8080"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - DB_SERVER_HOST=zabbix-db
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    depends_on:
      - zabbix-server
